# Настройки подключения к in-memory базе данных H2
spring.datasource.url=jdbc:h2:mem:jobdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Настройки инициализации схемы БД
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Включение удобной веб-консоли для просмотра БД
spring.h2.console.enabled=true
spring.application.name=job-tracking